config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'english', to: 'pages#index'
  get 'download_fr'=> 'pages#download_pdf_fr'
  get 'download_en'=> 'pages#download_pdf_en'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def download_pdf_en
    send_file(
      "#{Rails.root}/public/TEST.pdf",
      filename: "TEST.pdf",
      type: "application/pdf"
    )
  end

  def download_pdf_fr
    send_file(
      "#{Rails.root}/public/CV_Camille_LAGUERRE_2022_FR.pdf",
      filename: "CV_Camille_LAGUERRE.pdf",
      type: "application/pdf"
    )
  end

  def index
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <%# <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"> %>
    <%= favicon_link_tag asset_path('favicon-32x32.png') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="home-page" class="">
  <div id="home-top-page">
    <header>
      <div class="navbar">
        <%= link_to image_tag("test-logo-contours.png"), root_path, class:"logo" %>
        <nav class="desktop-navbar">
          <a href="#" class="active">home</a>
          <a class="cv-scroll">CV</a>
          <a class="about-btn">A propos</a>
          <a class="contact-btn">Contact</a>
        </nav>
        <nav class="mobile-navbar">
          <%= image_tag "menu", class: "menu nav-open" %>
          <%= image_tag "croix", class: "croix" %>
        </nav>
      </div>
      <div class="nav-list">
        <ul class="mobile-nav-item">
          <li> <a href="#" class="active">home</a></li>
          <li><a class="cv-scroll">CV</a></li>
          <li><a class="about-btn">A propos</a></li>
          <li><a class="contact-btn">Contact</a></li>
        </ul>
      </div>
    </header>
    <div id="header">
      <div id="name-title">
      <h1 id="name">Camille LAGUERRE</h1>
      <h2 id="job-title">DÉVELOPPEUSE WEB JUNIOR</h2>
    </div>
    <div class="about-btn-svg">
      <svg version="1.1" viewBox="0 0 700 700" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <defs>
          <symbol id="d" overflow="visible">
          <path d="m39.078-2.3281c-2.0117 1.043-4.1094 1.8281-6.2969 2.3594s-4.4648 0.79688-6.8281 0.79688c-7.0859 0-12.699-1.9766-16.844-5.9375-4.1367-3.957-6.2031-9.3281-6.2031-16.109 0-6.7891 2.0664-12.164 6.2031-16.125 4.1445-3.9688 9.7578-5.9531 16.844-5.9531 2.3633 0 4.6406 0.26562 6.8281 0.79688s4.2852 1.3242 6.2969 2.375v8.7969c-2.0312-1.3828-4.0391-2.3984-6.0156-3.0469-1.9688-0.64453-4.0469-0.96875-6.2344-0.96875-3.9062 0-6.9844 1.2578-9.2344 3.7656-2.2422 2.5-3.3594 5.9531-3.3594 10.359 0 4.3867 1.1172 7.8359 3.3594 10.344 2.25 2.5 5.3281 3.75 9.2344 3.75 2.1875 0 4.2656-0.32031 6.2344-0.96875 1.9766-0.64453 3.9844-1.6602 6.0156-3.0469z"/>
          </symbol>
          <symbol id="c" overflow="visible">
          <path d="m16.031-40.953v9.0625h10.516v7.2812h-10.516v13.531c0 1.4805 0.28906 2.4805 0.875 3 0.59375 0.52344 1.7656 0.78125 3.5156 0.78125h5.2344v7.2969h-8.7344c-4.0312 0-6.8867-0.83594-8.5625-2.5156-1.6797-1.6875-2.5156-4.5391-2.5156-8.5625v-13.531h-5.0781v-7.2812h5.0781v-9.0625z"/>
          </symbol>
          <symbol id="b" overflow="visible">
          <path d="m26.594-27.234v-17.078h10.266v44.312h-10.266v-4.6094c-1.3984 1.875-2.9453 3.25-4.6406 4.125-1.6875 0.875-3.6406 1.3125-5.8594 1.3125-3.9297 0-7.1562-1.5625-9.6875-4.6875-2.5234-3.125-3.7812-7.1445-3.7812-12.062 0-4.9141 1.2578-8.9375 3.7812-12.062 2.5312-3.125 5.7578-4.6875 9.6875-4.6875 2.1953 0 4.1445 0.44531 5.8438 1.3281 1.707 0.88672 3.2578 2.2578 4.6562 4.1094zm-6.7188 20.656c2.1875 0 3.8516-0.79688 5-2.3906 1.1445-1.5938 1.7188-3.9102 1.7188-6.9531 0-3.0391-0.57422-5.3594-1.7188-6.9531-1.1484-1.5938-2.8125-2.3906-5-2.3906-2.168 0-3.8242 0.79688-4.9688 2.3906-1.1484 1.5938-1.7188 3.9141-1.7188 6.9531 0 3.043 0.57031 5.3594 1.7188 6.9531 1.1445 1.5938 2.8008 2.3906 4.9688 2.3906z"/>
          </symbol>
          <symbol id="a" overflow="visible">
          <path d="m21.875-6.5781c2.1758 0 3.8359-0.79688 4.9844-2.3906 1.1562-1.5938 1.7344-3.9102 1.7344-6.9531 0-3.0391-0.57812-5.3594-1.7344-6.9531-1.1484-1.5938-2.8086-2.3906-4.9844-2.3906-2.1875 0-3.8672 0.80469-5.0312 2.4062-1.168 1.6055-1.75 3.918-1.75 6.9375 0 3.0234 0.58203 5.3359 1.75 6.9375 1.1641 1.6055 2.8438 2.4062 5.0312 2.4062zm-6.7812-20.656c1.4062-1.8516 2.9609-3.2227 4.6719-4.1094 1.707-0.88281 3.6719-1.3281 5.8906-1.3281 3.9375 0 7.1641 1.5625 9.6875 4.6875 2.5195 3.125 3.7812 7.1484 3.7812 12.062 0 4.918-1.2617 8.9375-3.7812 12.062-2.5234 3.125-5.75 4.6875-9.6875 4.6875-2.2188 0-4.1836-0.44531-5.8906-1.3281-1.7109-0.88281-3.2656-2.2539-4.6719-4.1094v4.6094h-10.188v-44.312h10.188z"/>
          </symbol>
        </defs>
        <g>
          <path d="m205.92 50.75 140 140c1.168 1.168 2.6836 1.75 4.082 1.75s3.0352-0.58203 4.082-1.75l140-140c2.332-2.332 2.332-5.9492 0-8.2852-2.332-2.332-5.9492-2.332-8.2852 0l-135.8 135.92-135.92-135.8c-2.332-2.332-5.9492-2.332-8.2852 0-2.332 2.3359-2.2148 5.9531 0.12109 8.168z"/>
          <path d="m205.92 377.42 140 140c1.168 1.168 2.6836 1.75 4.082 1.75s3.0352-0.58203 4.082-1.75l140-140c2.332-2.332 2.332-5.9492 0-8.2852-2.332-2.332-5.9492-2.332-8.2852 0l-135.8 135.92-135.92-135.8c-2.332-2.332-5.9492-2.332-8.2852 0-2.332 2.332-2.2148 5.9492 0.12109 8.168z"/>
          <path d="m205.92 214.08 140 140c1.168 1.168 2.6836 1.75 4.082 1.75s3.0352-0.58203 4.082-1.75l140-140c2.332-2.332 2.332-5.9492 0-8.2852-2.332-2.332-5.9492-2.332-8.2852 0l-135.8 135.92-135.92-135.8c-2.332-2.332-5.9492-2.332-8.2852 0-2.332 2.332-2.2148 5.9492 0.12109 8.1641z"/>
          <use x="70" y="735" xlink:href="#d"/>
          <use x="220.503906" y="735" xlink:href="#c"/>
          <use x="287.953125" y="735" xlink:href="#b"/>
          <use x="350.015625" y="735" xlink:href="#a"/>
          <use x="450.105469" y="735" xlink:href="#a"/>
        </g>
      </svg>
    </div>
    </div>
  </div>
  <%# __________________________________________________________________________________________________________________________________ %>
  <div>
    <div class="first-part">
      <div>
        <div id="about" class="title">
          <h1>À PROPOS</h1>
          <div class="line"></div>
        </div>
        <div class="about-content" data-aos="zoom-out-down">
          <p class="">
            Je suis Camille, j'ai grandi en Île-de-France, passionnée, la danse a rythmé ma vie. 
            À mes 30 ans, je me lance un nouveau défi : passer la frontière Suisse et repartir à zéro. <br/>
            Nouveau pays, nouvel environnement, pourquoi ne pas se fixer de nouveaux objectifs ?

            Après 5 ans à la SNCF, je me sentais prête à bouleverser ma carrière et me voici lancée dans 
            la formation du Wagon pour être développeuse web.
            Ces 6 mois de formation m'ont permis de développer mon savoir technique et mon sens de l'écoute.
            Cela me passionne et me donne envie d'en apprendre encore plus.
            Je suis maintenant prête à acquérir une première expérience professionnelle.
          </p>
        </div>
      </div>
      <%# <div class="profile-picture"> %>
        <%= image_tag "my_face.jpg", class:"profile-picture" %>
      <%# </div> %>
    </div>
    <div class="second-part">
      <div id="project" class="justify">
        <div class="title">
          <h1>PROJETS</h1>
          <div class="line"></div>
        </div>
        <div class="project-picture">
          <div class="candiloc">
            <div>
              <a href="https://candiloc.herokuapp.com/" target="_blank"><%= image_tag "CANDILOC.png" %></a>
            </div>
            <div class="candi-content">
              <h3>CANDILOC</h3>
              <h4>Louez votre candidat politique préféré.</h4>
              <p>
                <span class="underline">OBJECTIF</span> : création d'un site de location type "airbnb" avec un tout autre thème.
                <br/>
                <span class="underline">TEMPS</span> : 1 semaine
                <br/>
                Application web réalisée en équipe lors de ma formation au Wagon.<br/>
              </p>
            </div>
          </div>
          <div class="line"></div>
          <div class="pets">
            <div class="pets-content">
              <h3>PLACE FOR PETS</h3>
              <h4>Vous partez en vacances ? Eux aussi.</h4>
              <p>
                <span class="underline">OBJECTIF</span> : Réalisation d'une application qui calcule en temps réel le nombre de place restante dans des pensions à une courte distance d'un trajet en fonction du type d'animal.
                <br/>
                <span class="underline">TEMPS</span> : 3 semaines
                <br/>
                Application web format mobile (390x844) réalisée en équipe lors de ma formation au Wagon.<br/>
              </p>
            </div>
            <div>
              <a href="https://www.placeforpets.xyz/" target="_blank"><%= image_tag "PLACE_FOR_PETS.png" %></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="third-part">
      <div id="cv" class="title">
        <h1>COMPÉTENCES</h1>
        <div class="line"></div>
        <div class="skills">
          <ul class="skills-content">
            <li id="ruby" data-aos="zoom-in-up"><%= image_tag "logo-ruby--.png" %></li>
            <li id="rails" data-aos="zoom-in-up" data-aos-delay="200"><%= image_tag "logo-rails.png" %></a></li>
            <li id="html" data-aos="zoom-in-up" data-aos-delay="250"><%= image_tag "logo-html.png" %></a></li>
            <li id="css" data-aos="zoom-in-up" data-aos-delay="300"><%= image_tag "logo-css.png" %></a></li>
            <li id="js" data-aos="zoom-in-up" data-aos-delay="350"><%= image_tag "logo-js.png" %></a></li>
            <li id="figma" data-aos="zoom-in-up" data-aos-delay="400"><%= image_tag "logo-figma--.png" %></a></li>
            <li id="heroku" data-aos="zoom-in-up" data-aos-delay="450"><%= image_tag "logo-heroku.png" %></a></li>
          </ul>
        </div> 
        <div class="cv">
          <h1>CURRICULUM VITAE</h1> 
          <div class="line"></div>
          <div id="cv-link" data-aos="zoom-in" data-aos-duration="2000" data-aos-offset="0">
            <p>Mon profil vous intéresse ?</p>
            <%# <%= link_to "TÉLÉCHARGEZ LE CV", class:'', :action => :download_pdf_fr, :file_name => "CV_Camille_LAGUERRE_2022_FR.pdf" %>     
            <%= link_to "TÉLÉCHARGEZ LE CV", asset_path("CV_Camille_LAGUERRE_2022_FR.pdf", type: :pdf, target: "_blank", skip_pipeline: true) %>
          </div>
        </div>
      </div>
    </div>
    <div class="last-part">
      <div id="footer" class="title">
        <h1>CONTACT</h1>
        <div class="line"></div>
        <div class="footer-content">
          <%# <div class="ad-mail">
            <ul>
              <li class="ad-content">
                <p  data-aos="zoom-out-down">1618 Châtel-Saint-Denis<br/>
                SUISSE</p>
              </li>
              <li class="mail-content">
                <p data-aos="zoom-out-down">contact@camille-lgrr.com</p>
              </li>
            </ul>
          </div> %>
          <div class="contact-list">
            <ul>
              <li id="address">
                <%= image_tag "address.png" %> 
                <p  data-aos="fade-down" data-aos-duration="3000" data-aos-delay="400" data-aos-offset="0">  1618 Châtel-Saint-Denis  <br/>
                  SUISSE  </p>
              </li>
              <li id="linkedin">
                <a href="https://www.linkedin.com/in/camille-lgrr/" target="_blank">
                  <%= image_tag "linkedin.png" %>
                  <p data-aos="fade-down" data-aos-duration="3000" data-aos-delay="300" data-aos-offset="0">  linkedin.com/in/camille-lgrr  </p>
                </a>
              </li>
              <li id="github">
                <a href="https://github.com/Caaam333" target="_blank">
                  <%= image_tag "github.png" %>
                  <p  data-aos="fade-down" data-aos-duration="3000" data-aos-delay="200" data-aos-offset="0">  github.com/Caaam333  </p>
                </a>
              </li>
              <li id="email">
                <%= image_tag "email.png" %>
                <p  data-aos="fade-down" data-aos-duration="3000" data-aos-offset="0">  contact@camille-lgrr.com  </p>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div id="home-page">
  <div id="header">
    <div class="en-fr">
      <%= link_to image_tag("france.png"), root_path  %>
      <%= link_to image_tag("usa.png"), english_path, class:"active" %>
    </div>
    <div id="name-title">
      <h1 id="name">Camille LAGUERRE</h1>
      <h2 id="job-title">WEB DEVELOPER JUNIOR</h2>
    </div>
    <div class="about-btn">
      <svg version="1.1" viewBox="0 0 700 700" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <defs>
          <symbol id="d" overflow="visible">
          <path d="m39.078-2.3281c-2.0117 1.043-4.1094 1.8281-6.2969 2.3594s-4.4648 0.79688-6.8281 0.79688c-7.0859 0-12.699-1.9766-16.844-5.9375-4.1367-3.957-6.2031-9.3281-6.2031-16.109 0-6.7891 2.0664-12.164 6.2031-16.125 4.1445-3.9688 9.7578-5.9531 16.844-5.9531 2.3633 0 4.6406 0.26562 6.8281 0.79688s4.2852 1.3242 6.2969 2.375v8.7969c-2.0312-1.3828-4.0391-2.3984-6.0156-3.0469-1.9688-0.64453-4.0469-0.96875-6.2344-0.96875-3.9062 0-6.9844 1.2578-9.2344 3.7656-2.2422 2.5-3.3594 5.9531-3.3594 10.359 0 4.3867 1.1172 7.8359 3.3594 10.344 2.25 2.5 5.3281 3.75 9.2344 3.75 2.1875 0 4.2656-0.32031 6.2344-0.96875 1.9766-0.64453 3.9844-1.6602 6.0156-3.0469z"/>
          </symbol>
          <symbol id="c" overflow="visible">
          <path d="m16.031-40.953v9.0625h10.516v7.2812h-10.516v13.531c0 1.4805 0.28906 2.4805 0.875 3 0.59375 0.52344 1.7656 0.78125 3.5156 0.78125h5.2344v7.2969h-8.7344c-4.0312 0-6.8867-0.83594-8.5625-2.5156-1.6797-1.6875-2.5156-4.5391-2.5156-8.5625v-13.531h-5.0781v-7.2812h5.0781v-9.0625z"/>
          </symbol>
          <symbol id="b" overflow="visible">
          <path d="m26.594-27.234v-17.078h10.266v44.312h-10.266v-4.6094c-1.3984 1.875-2.9453 3.25-4.6406 4.125-1.6875 0.875-3.6406 1.3125-5.8594 1.3125-3.9297 0-7.1562-1.5625-9.6875-4.6875-2.5234-3.125-3.7812-7.1445-3.7812-12.062 0-4.9141 1.2578-8.9375 3.7812-12.062 2.5312-3.125 5.7578-4.6875 9.6875-4.6875 2.1953 0 4.1445 0.44531 5.8438 1.3281 1.707 0.88672 3.2578 2.2578 4.6562 4.1094zm-6.7188 20.656c2.1875 0 3.8516-0.79688 5-2.3906 1.1445-1.5938 1.7188-3.9102 1.7188-6.9531 0-3.0391-0.57422-5.3594-1.7188-6.9531-1.1484-1.5938-2.8125-2.3906-5-2.3906-2.168 0-3.8242 0.79688-4.9688 2.3906-1.1484 1.5938-1.7188 3.9141-1.7188 6.9531 0 3.043 0.57031 5.3594 1.7188 6.9531 1.1445 1.5938 2.8008 2.3906 4.9688 2.3906z"/>
          </symbol>
          <symbol id="a" overflow="visible">
          <path d="m21.875-6.5781c2.1758 0 3.8359-0.79688 4.9844-2.3906 1.1562-1.5938 1.7344-3.9102 1.7344-6.9531 0-3.0391-0.57812-5.3594-1.7344-6.9531-1.1484-1.5938-2.8086-2.3906-4.9844-2.3906-2.1875 0-3.8672 0.80469-5.0312 2.4062-1.168 1.6055-1.75 3.918-1.75 6.9375 0 3.0234 0.58203 5.3359 1.75 6.9375 1.1641 1.6055 2.8438 2.4062 5.0312 2.4062zm-6.7812-20.656c1.4062-1.8516 2.9609-3.2227 4.6719-4.1094 1.707-0.88281 3.6719-1.3281 5.8906-1.3281 3.9375 0 7.1641 1.5625 9.6875 4.6875 2.5195 3.125 3.7812 7.1484 3.7812 12.062 0 4.918-1.2617 8.9375-3.7812 12.062-2.5234 3.125-5.75 4.6875-9.6875 4.6875-2.2188 0-4.1836-0.44531-5.8906-1.3281-1.7109-0.88281-3.2656-2.2539-4.6719-4.1094v4.6094h-10.188v-44.312h10.188z"/>
          </symbol>
        </defs>
        <g>
          <path d="m205.92 50.75 140 140c1.168 1.168 2.6836 1.75 4.082 1.75s3.0352-0.58203 4.082-1.75l140-140c2.332-2.332 2.332-5.9492 0-8.2852-2.332-2.332-5.9492-2.332-8.2852 0l-135.8 135.92-135.92-135.8c-2.332-2.332-5.9492-2.332-8.2852 0-2.332 2.3359-2.2148 5.9531 0.12109 8.168z"/>
          <path d="m205.92 377.42 140 140c1.168 1.168 2.6836 1.75 4.082 1.75s3.0352-0.58203 4.082-1.75l140-140c2.332-2.332 2.332-5.9492 0-8.2852-2.332-2.332-5.9492-2.332-8.2852 0l-135.8 135.92-135.92-135.8c-2.332-2.332-5.9492-2.332-8.2852 0-2.332 2.332-2.2148 5.9492 0.12109 8.168z"/>
          <path d="m205.92 214.08 140 140c1.168 1.168 2.6836 1.75 4.082 1.75s3.0352-0.58203 4.082-1.75l140-140c2.332-2.332 2.332-5.9492 0-8.2852-2.332-2.332-5.9492-2.332-8.2852 0l-135.8 135.92-135.92-135.8c-2.332-2.332-5.9492-2.332-8.2852 0-2.332 2.332-2.2148 5.9492 0.12109 8.1641z"/>
          <use x="70" y="735" xlink:href="#d"/>
          <use x="220.503906" y="735" xlink:href="#c"/>
          <use x="287.953125" y="735" xlink:href="#b"/>
          <use x="350.015625" y="735" xlink:href="#a"/>
          <use x="450.105469" y="735" xlink:href="#a"/>
        </g>
      </svg>
    </div>
  </div>
  <div class="justify">
    <div class="first-part">
      <div id="about">
        <h1>ABOUT</h1>
        <div class="line"></div>
        <div class="about-content">
          <p class="row">
            I'm Camille, I grew up in the Paris region, passionate, dance has punctuated my life. 
            When I turn 30, I set myself a new challenge: cross the Swiss border and start from scratch.<br/>
            New country, new environment, why not set new goals?
            After 5 years at the SNCF, I felt ready to turn my career upside down and here I am launched in 
            Le Wagon training to be a web developer.
          </p>
          <p class="row2">
            These 6 months of training allowed me to develop my technical knowledge and my listening skills. 
            It bothers me and makes me want to learn even more.
            I am now ready to acquire a first professional experience.
          </p>
        </div>
      </div>
      <div class="profile-picture">
        <%= image_tag "my_face.jpg" %>
      </div>
    </div>
    <div class="second-part">
      <div id="project">
        <h1>PROJECTS</h1>
        <div class="line"></div>
        <div class="project-picture">
          <div class="candiloc">
            <a href="https://candiloc.herokuapp.com/" target="_blank"><%= image_tag "CANDILOC.png" %></a>
            <div class="candi-content">
              <h3>CANDILOC</h3>
              <h4>Rent your favorite politician.</h4>
              <p>
                GOAL : creation of an "airbnb" type rental site with a completely different theme.
                <br/>
                Web application created as a team during my training at Le Wagon.<br/>
              </p>
            </div>
          </div>
          <div class="line"></div>
          <div class="pets">
            <div class="pets-content">
              <h3>PLACE FOR PETS</h3>
              <h4>Vous partez en vacances ? Eux aussi.</h4>
              <p>
                GOAL : Realization of an application which calculates in real time the number of places remaining in pensions at a short distance of a journey according to the type of animal.
                <br/>
                Web application created as a team during my training at Le Wagon.<br/>
              </p>
            </div>
            <%= image_tag "PLACE_FOR_PETS.png" %> 
          </div>
        </div>
      </div>
    </div>
    <div class="third-part">
      <div id="cv">
        <div>
          <h1>CURRICULUM VITAE</h1>
          <div class="line"></div>
        </div>
        <div class="skills">
          <ul class="skills-content">
            <li id="ruby"><%= image_tag "logo-ruby.png" %></li>
            <li id="rails"><%= image_tag "logo-rails.png" %></a></li>
            <li id="html"><%= image_tag "logo-html.png" %></a></li>
            <li id="css"><%= image_tag "logo-css.png" %></a></li>
            <li id="js"><%= image_tag "logo-js.png" %></a></li>
            <li id="figma"><%= image_tag "logo-figma.png" %></a></li>
            <li id="heroku"><%= image_tag "logo-heroku.png" %></a></li>
            <li id="ruby"><%= image_tag "logo-ruby.png" %></li>
            <li id="rails"><%= image_tag "logo-rails.png" %></a></li>
            <li id="html"><%= image_tag "logo-html.png" %></a></li>
            <li id="css"><%= image_tag "logo-css.png" %></a></li>
            <li id="js"><%= image_tag "logo-js.png" %></a></li>
            <li id="figma"><%= image_tag "logo-figma.png" %></a></li>
            <li id="heroku"><%= image_tag "logo-heroku.png" %></a></li>
          </ul>
        </div>  
        <div id="cv-link" >
          <p>Interested ?</p>
          <%= link_to "DOWNLOAD MY CV" ,:action => :download_pdf_en, :file_name => "TEST.pdf" %>    
        </div>
      </div>
      
    </div>
    <div class="last-part">
      <div id="footer">
        <div>
          <h1>CONTACT</h1>
          <div class="line"></div>
        </div>
        <div id="ad" class="cache">
          adresse-mail@gmail.com
        </div>
        <div class="contact-list">
          <ul>
            <li id="address"><%= image_tag "address.png" %></li>
            <li id="linkedin"><a href="https://www.linkedin.com/in/camille-lgrr/"><%= image_tag "linkedin.png" %></a></li>
            <li id="email"><a href="#"><%= image_tag "email.png" %></a></li>
            <li id="github"><a href="https://github.com/Caaam333"><%= image_tag "github.png" %></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>